-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 15:04:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controleestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controleestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controleestoque` DEFAULT CHARACTER SET utf8 ;
USE `controleestoque` ;

-- -----------------------------------------------------
-- Table `controleestoque`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`Usuario` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(75) NOT NULL,
  `Password` VARCHAR(75) NOT NULL,
  `Dataregistro` DATE NOT NULL,
  `Permissao` TINYINT NOT NULL,
  `Imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`Produto` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`Produto` (
  `CodRefProduto` INT NOT NULL AUTO_INCREMENT,
  `NomeProduto` VARCHAR(75) NOT NULL,
  `Usuario_idUser` INT NOT NULL,
  PRIMARY KEY (`CodRefProduto`),
  INDEX `fk_Produto_Usuario1_idx` (`Usuario_idUser` ASC),
  CONSTRAINT `fk_Produto_Usuario1`
    FOREIGN KEY (`Usuario_idUser`)
    REFERENCES `controleestoque`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`Fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`Fabricante` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`Fabricante` (
  `idFabricante` INT NOT NULL AUTO_INCREMENT,
  `NomeFabricante` VARCHAR(75) NOT NULL,
  `CNPJFabricante` VARCHAR(75) NOT NULL,
  `EmailFabricante` VARCHAR(75) NOT NULL,
  `EnderecoFabricante` VARCHAR(75) NOT NULL,
  `TelefoneFabricante` VARCHAR(45) NOT NULL,
  `Usuario_idUser` INT NOT NULL,
  PRIMARY KEY (`idFabricante`),
  INDEX `fk_Fabricante_Usuario1_idx` (`Usuario_idUser` ASC),
  CONSTRAINT `fk_Fabricante_Usuario1`
    FOREIGN KEY (`Usuario_idUser`)
    REFERENCES `controleestoque`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`Representante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`Representante` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`Representante` (
  `idRepresentante` INT NOT NULL AUTO_INCREMENT,
  `NomeRepresentante` VARCHAR(75) NOT NULL,
  `TelefoneRepresentante` VARCHAR(45) NOT NULL,
  `EmailRepresentante` VARCHAR(45) NOT NULL,
  `Fabricante_idFabricante` INT NOT NULL,
  `Usuario_idUser` INT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  INDEX `fk_Representante_Fabricante1_idx` (`Fabricante_idFabricante` ASC),
  INDEX `fk_Representante_Usuario1_idx` (`Usuario_idUser` ASC),
  CONSTRAINT `fk_Representante_Fabricante1`
    FOREIGN KEY (`Fabricante_idFabricante`)
    REFERENCES `controleestoque`.`Fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Representante_Usuario1`
    FOREIGN KEY (`Usuario_idUser`)
    REFERENCES `controleestoque`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`Itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`Itens` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`Itens` (
  `idItens` INT NOT NULL AUTO_INCREMENT,
  `QuantItens` INT NOT NULL,
  `QuantItensVend` INT NOT NULL,
  `ValCompItens` DECIMAL NOT NULL,
  `ValVendItens` DECIMAL NOT NULL,
  `DataCompraItens` DATETIME NOT NULL,
  `DataVenci_Itens` DATETIME NULL,
  `Ativo` TINYINT NOT NULL,
  `Produto_CodRefProduto` INT NOT NULL,
  `Fabricante_idFabricante` INT NOT NULL,
  `Usuario_idUser` INT NOT NULL,
  PRIMARY KEY (`idItens`),
  INDEX `fk_Itens_Produto1_idx` (`Produto_CodRefProduto` ASC),
  INDEX `fk_Itens_Fabricante1_idx` (`Fabricante_idFabricante` ASC),
  INDEX `fk_Itens_Usuario1_idx` (`Usuario_idUser` ASC),
  CONSTRAINT `fk_Itens_Produto1`
    FOREIGN KEY (`Produto_CodRefProduto`)
    REFERENCES `controleestoque`.`Produto` (`CodRefProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Fabricante1`
    FOREIGN KEY (`Fabricante_idFabricante`)
    REFERENCES `controleestoque`.`Fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Usuario1`
    FOREIGN KEY (`Usuario_idUser`)
    REFERENCES `controleestoque`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`escopo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`escopo` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`escopo` (
  `esccod` INT NOT NULL AUTO_INCREMENT,
  `escnome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`esccod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`usuario2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`usuario2` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`usuario2` (
  `usucod` INT NOT NULL AUTO_INCREMENT,
  `usunome` VARCHAR(50) NOT NULL,
  `usuemail` VARCHAR(50) NOT NULL,
  `ususenha` VARCHAR(50) NOT NULL,
  `usuimagem` VARCHAR(100) NULL,
  `usufone` VARCHAR(20) NOT NULL,
  `escopo_esccod` INT NOT NULL,
  `usupermissao` INT NOT NULL,
  PRIMARY KEY (`usucod`),
  INDEX `fk_usuario_escopo1_idx` (`escopo_esccod` ASC),
  CONSTRAINT `fk_usuario_escopo1`
    FOREIGN KEY (`escopo_esccod`)
    REFERENCES `controleestoque`.`escopo` (`esccod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`motorista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`motorista` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`motorista` (
  `motcod` INT NOT NULL,
  `motnome` VARCHAR(45) NULL,
  `motrua` VARCHAR(45) NULL,
  `motbairro` VARCHAR(45) NULL,
  `motcidade` VARCHAR(45) NULL,
  `motestado` VARCHAR(45) NULL,
  `motemail` VARCHAR(45) NULL,
  `motsenha` VARCHAR(45) NULL,
  `motfone` VARCHAR(45) NULL,
  `motcpf` VARCHAR(45) NULL,
  `motrg` VARCHAR(45) NULL,
  `motcnh` VARCHAR(45) NULL,
  `motdtadmissao` VARCHAR(45) NULL,
  `motdtafast` VARCHAR(45) NULL,
  `motsituacao` VARCHAR(45) NULL,
  PRIMARY KEY (`motcod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`jorinter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`jorinter` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`jorinter` (
  `jorintercod` INT NOT NULL AUTO_INCREMENT,
  `jorinterinicial` DATETIME NULL,
  `jorinterfinal` DATETIME NULL,
  PRIMARY KEY (`jorintercod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`jorref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`jorref` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`jorref` (
  `jorrefcod` INT NOT NULL AUTO_INCREMENT,
  `jorrefinicial` DATETIME NULL,
  `jorreffinal` DATETIME NULL,
  PRIMARY KEY (`jorrefcod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`joresp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`joresp` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`joresp` (
  `jorespcod` INT NOT NULL AUTO_INCREMENT,
  `jorespinicial` DATETIME NULL,
  `jorespfinal` DATETIME NULL,
  PRIMARY KEY (`jorespcod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`estado` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`estado` (
  `estcod` INT NOT NULL AUTO_INCREMENT,
  `estnome` VARCHAR(50) NOT NULL,
  `estsigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estcod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`cidade` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`cidade` (
  `cidcod` INT NOT NULL AUTO_INCREMENT,
  `cidnome` VARCHAR(50) NOT NULL,
  `estado_estcod` INT NOT NULL,
  PRIMARY KEY (`cidcod`),
  INDEX `fk_cidade_estado1_idx` (`estado_estcod` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_estcod`)
    REFERENCES `controleestoque`.`estado` (`estcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`tpveiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`tpveiculo` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`tpveiculo` (
  `tpvcod` INT NOT NULL,
  `tpvnome` VARCHAR(45) NULL,
  PRIMARY KEY (`tpvcod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`veiculo` (
  `veicod` INT NOT NULL AUTO_INCREMENT,
  `veiplaca` VARCHAR(10) NULL,
  `veiano` VARCHAR(45) NULL,
  `veimodelo` VARCHAR(45) NULL,
  `tpveiculo_tpvcod` INT NOT NULL,
  PRIMARY KEY (`veicod`),
  INDEX `fk_veiculo_tpveiculo1_idx` (`tpveiculo_tpvcod` ASC),
  CONSTRAINT `fk_veiculo_tpveiculo1`
    FOREIGN KEY (`tpveiculo_tpvcod`)
    REFERENCES `controleestoque`.`tpveiculo` (`tpvcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`jornada` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`jornada` (
  `jorcod` INT NOT NULL,
  `jortitulo` VARCHAR(45) NULL,
  `jordia` VARCHAR(45) NULL,
  `jorhorainicio` VARCHAR(45) NULL,
  `jorhorafinal` VARCHAR(45) NULL,
  `jorhoraext` VARCHAR(45) NULL,
  `jordescanso` VARCHAR(45) NULL,
  `motorista_motcod` INT NOT NULL,
  `jorinter_jorintercod` INT NOT NULL,
  `jorref_jorrefcod` INT NOT NULL,
  `joresp_jorespcod` INT NOT NULL,
  `cidade_cidcod` INT NOT NULL,
  `veiculo_veicod` INT NOT NULL,
  `jornada_jorcod` INT NOT NULL,
  `usuario2_usucod` INT NOT NULL,
  PRIMARY KEY (`jorcod`),
  INDEX `fk_jornada_motorista1_idx` (`motorista_motcod` ASC),
  INDEX `fk_jornada_jorinter1_idx` (`jorinter_jorintercod` ASC),
  INDEX `fk_jornada_jorref1_idx` (`jorref_jorrefcod` ASC),
  INDEX `fk_jornada_joresp1_idx` (`joresp_jorespcod` ASC),
  INDEX `fk_jornada_cidade1_idx` (`cidade_cidcod` ASC),
  INDEX `fk_jornada_veiculo1_idx` (`veiculo_veicod` ASC),
  INDEX `fk_jornada_jornada1_idx` (`jornada_jorcod` ASC),
  INDEX `fk_jornada_usuario21_idx` (`usuario2_usucod` ASC),
  CONSTRAINT `fk_jornada_motorista1`
    FOREIGN KEY (`motorista_motcod`)
    REFERENCES `controleestoque`.`motorista` (`motcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_jorinter1`
    FOREIGN KEY (`jorinter_jorintercod`)
    REFERENCES `controleestoque`.`jorinter` (`jorintercod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_jorref1`
    FOREIGN KEY (`jorref_jorrefcod`)
    REFERENCES `controleestoque`.`jorref` (`jorrefcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_joresp1`
    FOREIGN KEY (`joresp_jorespcod`)
    REFERENCES `controleestoque`.`joresp` (`jorespcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_cidade1`
    FOREIGN KEY (`cidade_cidcod`)
    REFERENCES `controleestoque`.`cidade` (`cidcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_veiculo1`
    FOREIGN KEY (`veiculo_veicod`)
    REFERENCES `controleestoque`.`veiculo` (`veicod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_jornada1`
    FOREIGN KEY (`jornada_jorcod`)
    REFERENCES `controleestoque`.`jornada` (`jorcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_usuario21`
    FOREIGN KEY (`usuario2_usucod`)
    REFERENCES `controleestoque`.`usuario2` (`usucod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleestoque`.`regrasjornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controleestoque`.`regrasjornada` ;

CREATE TABLE IF NOT EXISTS `controleestoque`.`regrasjornada` (
  `rjocod` INT NOT NULL,
  `rjotrabinint` VARCHAR(45) NULL,
  `rjodesc` VARCHAR(45) NULL,
  `rjodescinint` VARCHAR(45) NULL,
  `rjorefeicao` VARCHAR(45) NULL,
  `rjomaxdia` VARCHAR(45) NULL,
  `rjoextra` VARCHAR(45) NULL,
  `rjoesprep` VARCHAR(45) NULL,
  `rjodescinter` VARCHAR(45) NULL,
  `tpveiculo_tpvcod` INT NOT NULL,
  `jornada_jorcod` INT NOT NULL,
  PRIMARY KEY (`rjocod`),
  INDEX `fk_regrasjornada_tpveiculo1_idx` (`tpveiculo_tpvcod` ASC),
  INDEX `fk_regrasjornada_jornada1_idx` (`jornada_jorcod` ASC),
  CONSTRAINT `fk_regrasjornada_tpveiculo1`
    FOREIGN KEY (`tpveiculo_tpvcod`)
    REFERENCES `controleestoque`.`tpveiculo` (`tpvcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regrasjornada_jornada1`
    FOREIGN KEY (`jornada_jorcod`)
    REFERENCES `controleestoque`.`jornada` (`jorcod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
