-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 15:51:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controledejornada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controledejornada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controledejornada` DEFAULT CHARACTER SET utf8 ;
USE `controledejornada` ;

-- -----------------------------------------------------
-- Table `controledejornada`.`regrasjornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controledejornada`.`regrasjornada` ;

CREATE TABLE IF NOT EXISTS `controledejornada`.`regrasjornada` (
  `rjocod` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `rjonome` VARCHAR(45) NULL,
  `rjotrabinint` TIME NULL,
  `rjodesc` TIME NULL,
  `rjodescinint` TIME NULL,
  `rjorefeicao` TIME NULL,
  `rjomaxdia` TIME NULL,
  `rjoextra` TIME NULL,
  `rjoesprep` TIME NULL,
  `rjodescinter` TIME NULL,
  PRIMARY KEY (`rjocod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejornada`.`motorista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controledejornada`.`motorista` ;

CREATE TABLE IF NOT EXISTS `controledejornada`.`motorista` (
  `motcod` INT NOT NULL,
  `motnome` VARCHAR(45) NULL,
  `motrua` VARCHAR(45) NULL,
  `motbairro` VARCHAR(45) NULL,
  `motcidade` VARCHAR(45) NULL,
  `motestado` VARCHAR(45) NULL,
  `motemail` VARCHAR(45) NULL,
  `motsenha` VARCHAR(45) NULL,
  `motfone` VARCHAR(45) NULL,
  `motcpf` VARCHAR(45) NULL,
  `motrg` VARCHAR(45) NULL,
  `motcnh` VARCHAR(45) NULL,
  `motdtadmissao` VARCHAR(45) NULL,
  `motdtafast` VARCHAR(45) NULL,
  `motsituacao` VARCHAR(45) NULL,
  `regrasjornada_rjocod` INT NOT NULL,
  PRIMARY KEY (`motcod`),
  INDEX `fk_motorista_regrasjornada1_idx` (`regrasjornada_rjocod` ASC),
  CONSTRAINT `fk_motorista_regrasjornada1`
    FOREIGN KEY (`regrasjornada_rjocod`)
    REFERENCES `controledejornada`.`regrasjornada` (`rjocod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
